# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: Docker@2
  displayName: 'Build docker'
  inputs:
    containerRegistry: 'dockerhub1'
    repository: ddschmid/pipelines-dotnet-core-docker
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  displayName: 'Login to docker'
  inputs:
    containerRegistry: 'dockerhub1'
    command: 'login'

- task: Docker@2
  displayName: 'Push to docker'
  inputs:
    containerRegistry: 'dockerhub1'
    repository: ddschmid/pipelines-dotnet-core-docker
    command: 'push'

- task: Docker@2
  displayName: 'Logout docker'
  inputs:
    containerRegistry: 'dockerhub1'
    command: 'logout'
